# This CI configuration is used for landing page deployment in external GitLab
# instances.
#
# To use it, go into the "CI/CD settings" of that repository and input
# ".gitlab-ci-deployment.yml" in the "CI/CD configuration file" field under the
# "General pipelines" section.
---
# Right now we're sticking to Python 3.8 due to dependency issues.
image: python:3.8-bullseye

variables:
  TRANSLATION_BRANCH: onion-support-landing-page
  LEKTOR_FOREGROUND_COLOR: 'CF5C00'
  LEKTOR_BACKGROUND_COLOR: 'EA6903'
  LEKTOR_BUTTON_COLOR: 'EA6903'
  LEKTOR_ONION_URL_LOCK_FILTER: 'invert(43%) sepia(95%) saturate(2236%) hue-rotate(4deg) brightness(97%) contrast(98%);'
  LEKTOR_ONION_URL: 'https://abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz1234.onion'
  LEKTOR_SERVICE_NAME: 'Onion Launchpad'
  LEKTOR_SERVICE_URL: 'https://service-url.website/'
  LEKTOR_FAVICON: '/favicon-default-32.png'
  LEKTOR_LOGO_PATH: '/logo-default.svg'
  LEKTOR_ASSET_REPOSITORY_URL: ''

pages:
  script:
    - scripts/provision
    - scripts/build
  artifacts:
    paths:
      - public
  only:
    - main
