# This CI configuration is used for landing page deployment in external GitLab
# instances.
#
# To use it, go into the "CI/CD settings" of that repository and input
# ".gitlab-ci-deployment.yml" in the "CI/CD configuration file" field under the
# "General pipelines" section.
---
image: python:3.11-bullseye

variables:
  TRANSLATION_BRANCH: onion-launchpad
  LEKTOR_FOREGROUND_COLOR: 'CF5C00'
  LEKTOR_BACKGROUND_COLOR: 'EA6903'
  LEKTOR_BUTTON_COLOR: 'EA6903'
  LEKTOR_ONION_URL_LOCK_FILTER: 'CF5C00'
  LEKTOR_ONION_URL: 'https://abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz2345.onion'
  LEKTOR_SERVICE_NAME: 'Onion Launchpad'
  LEKTOR_SERVICE_URL: 'https://service-url.website/'
  LEKTOR_FAVICON: '/favicon-default-32.png'
  LEKTOR_LOGO_PATH: '/onion-launchpad-logo-default-1.svg'
  LEKTOR_ASSET_REPOSITORY_URL: ''
  LEKTOR_DEFAULT_LANGUAGE: ''
  LEKTOR_AVAILABLE_LANGUAGES: ''
  LEKTOR_ANALYTICS: ''
  LEKTOR_ANALYTICS_BACKEND: ''
  LEKTOR_ANALYTICS_SITE_ID: '1'
  LEKTOR_ANALYTICS_LINK_TRACKING: ''
  LEKTOR_ANALYTICS_BROWSER_DETECTION: ''
  LEKTOR_ANALYTICS_PRIVACY_POLICY_URL: ''
  LEKTOR_ANALYTICS_BACKGROUND_COLOR: 'FCEDE1'

build:
  stage: build
  script:
    - scripts/provision
    - scripts/build
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - main

docs:
  image: debian:bookworm
  stage: build
  needs:
    - job: build
      artifacts: true
  script:
    - apt-get update
    - apt-get install -y git
    - git submodule sync
    - git submodule update --init --recursive --depth 1
    - vendors/onion-mkdocs/scripts/onion-mkdocs-provision-build
    - vendors/onion-mkdocs/scripts/onion-mkdocs-build
  artifacts:
    expire_in: 1 week
    paths:
      - public

pages:
  stage: build
  image: debian:bookworm
  needs:
    - job: docs
      artifacts: true
  artifacts:
    expire_in: 1 week
    paths:
      - public
