---
variables:
  TRANSLATION_BRANCH: onion-support-landing-page
  LEKTOR_FOREGROUND_COLOR: 'CF5C00'
  LEKTOR_BACKGROUND_COLOR: 'EA6903'
  LEKTOR_BUTTON_COLOR: 'EA6903'
  LEKTOR_ONION_URL_LOCK_FILTER: 'CF5C00'
  LEKTOR_ONION_URL: 'https://abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz1234.onion'
  LEKTOR_SERVICE_NAME: 'Onion Launchpad'
  LEKTOR_SERVICE_URL: 'https://service-url.website/'
  LEKTOR_FAVICON: '/favicon-default-32.png'
  LEKTOR_LOGO_PATH: '/onion-launchpad-logo-default-1.svg'
  LEKTOR_ASSET_REPOSITORY_URL: ''
  LEKTOR_DEFAULT_LANGUAGE: ''
  LEKTOR_AVAILABLE_LANGUAGES: ''
  LEKTOR_ANALYTICS: ''
  LEKTOR_ANALYTICS_BACKEND: ''
  LEKTOR_ANALYTICS_SITE_ID: '1'

include:
  - project: tpo/tpa/ci-templates
    file:
      - lektor.yml
      - pages-deploy.yml
