---
version: '3'

services:
  landing:
    image: "onion-launchpad/page:0.1"
    build:
      context: .
      dockerfile: Dockerfile
      # This needs a newer Docker Compose (>= 1.28)
      #target: landing
    volumes:
      - .:/srv/onion-launchpad
    ports:
      - "5000:5000"
    entrypoint: "scripts/server"
    restart: always
    # This needs a newer Docker Compose (>= 1.28)
    #profiles: ["api", "all"]
