image: python:3.8-bullseye

variables:
  TRANSLATION_BRANCH: onion-support-landing-page
  LEKTOR_FOREGROUND_COLOR: 'CF5C00'
  LEKTOR_BACKGROUND_COLOR: 'EA6903'
  LEKTOR_BUTTON_COLOR: 'EA6903'
  LEKTOR_ONION_URL_LOCK_FILTER: 'invert(43%) sepia(95%) saturate(2236%) hue-rotate(4deg) brightness(97%) contrast(98%);'
  LEKTOR_FAVICON: ''

pages:
  script:
    - scripts/provision
    - scripts/build
  artifacts:
    paths:
      - public
  only:
    - main
