image: python:3.8-bullseye

variables:
  TRANSLATION_BRANCH: onion-support-landing-page
  LEKTOR_FOREGROUND_COLOR: 'CF5C00'
  LEKTOR_BACKGROUND_COLOR: 'EA6903'
  LEKTOR_BUTTON_COLOR: 'EA6903'
  LEKTOR_ONION_URL_LOCK_FILTER: 'invert(43%) sepia(95%) saturate(2236%) hue-rotate(4deg) brightness(97%) contrast(98%);'
  LEKTOR_FAVICON: ''

pages:
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends gettext python3-babel python3-pip git python3-inifile python3-dev python3-setuptools python3-venv python3-openssl python3-cryptography -y
    - pip3 install babel
    - pip3 install wheel
    - pip3 install lektor
    - rm -rf i18n
    - git clone https://gitlab.torproject.org/tpo/translation.git i18n
    - cd i18n && git checkout onion-support-landing-page && cd ..
    - git clone https://gitlab.torproject.org/tpo/web/lego.git lego
    - cd lego && git submodule update --init --recursive && git pull origin main && cd ..
    - rm -rf public
    - lektor build --output-path public && lektor build --output-path public && lektor build --output-path public
  artifacts:
    paths:
      - public
  only:
    - main
